### ISSUE TITLE
Nothing to publish for tag [config].

### ISSUE THREAD

**Issue by iliasnaamane** [OmnipresentWorldOfWizkids/laravel-drive#1]
When I run php artisan vendor:publish --provider="OWOW\LaravelDrive\LaravelDriveServiceProvider" --tag="config"
 Nothing to publish for tag [config].

**Comment by dees040** [comment]
Try to run `php artisan vendor:publish` or just hard copy `vendor/owow/laravel-drive/config/drive.php` to `config/drive.php`.
